laravel-app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// 認証関連
Route::get('/login','Auth\LoginController@showLoginForm');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout','Auth\LoginController@logout')->name('logout');
Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    // ダッシュボード
    Route::get('/', 'Dashboard\DashboardController@index');

    // プロジェクト管理
    Route::get('/project', 'Project\ProjectController@index');
    Route::get('/project/create', 'Project\ProjectController@create');
    Route::post('/project/store', 'ReservationManagementController@storeProject');
    Route::get('/project/edit', 'Project\ProjectController@edit');
    Route::post('/project/update', 'Project\ProjectManagementController@update');
    Route::post('/project/checkHoliday', 'Project\ProjectManagementController@checkHoliday');
    Route::get('/project/show', 'Project\ProjectController@show');

    // 顧客管理
    Route::get('/client', 'Client\ClientController@index');
    Route::get('/client/create', 'Client\ClientController@create');
    Route::post('/client/store', 'ReservationManagementController@storeClient');
    Route::post('/client/storeQuick', 'ReservationManagementController@storeQuickClient');
    Route::get('/client/edit', 'Client\ClientController@edit');
    Route::post('/client/update', 'Client\ClientManagementController@update');
    Route::post('/client/show', 'Client\ClientManagementController@getClientData');

    // 請求管理
    Route::get('/invoice', 'Invoice\InvoiceController@index');
    Route::get('/invoice/create', 'Invoice\InvoiceController@create');
    Route::post('/invoice/store', 'ReservationManagementController@storeInvoice');
    Route::get('/invoice/edit', 'Invoice\InvoiceController@edit');
    Route::post('/invoice/update', 'Invoice\InvoiceManagementController@update');
    Route::post('/invoice/show', 'Invoice\InvoiceManagementController@getInvoiceData');

    // 入金管理
    Route::post('/payment', 'Payment\PaymentManagementController@payment');

    // 社員管理
    Route::get('/account','Account\AccountController@index');
    Route::get('/account/create','Account\AccountController@create');
    Route::post('/account/store','Account\AccountManagementController@store');
    Route::get('/account/edit','Account\AccountController@edit');
    Route::post('/account/update','Account\AccountManagementController@update');
    Route::get('/account/show', function () {

        $page = [
            'title' => '社員詳細',
            'dir' => ['account', 'show'],
        ];

        $data = [
            'page' => $page,
        ];

        return view('account/show')->with($data);
    });


    // 利用日当日
    Route::get('/use', 'Production\ProductionController@index');
    Route::post('/use/startUse', 'Production\ProductionManagementController@startUse');
    Route::post('/use/checkExtension', 'Production\ProductionManagementController@checkExtension');
    Route::post('/use/doExtension', 'Production\ProductionManagementController@doExtension');
    Route::post('/use/endStandbyUse', 'Production\ProductionManagementController@endStandbyUse');
    Route::post('/use/endUse', 'Production\ProductionManagementController@endUse');

});

// デバック
Route::get('/tr','Debug\DebugController@index');

// 初期画面
Route::get('/home', 'HomeController@index')->name('home');

laravel-app/app/Models/t_projects.php
<?php

namespace App\Models;

use App\Libs\Common;
use Illuminate\Database\Eloquent\Model;

class t_projects extends Model
{
    //
    protected $table = 't_projects';
    protected $primaryKey = 'project_id';

    protected $fillable = [
        'project_id','project_name','project_comment','google_calendar_code','client_id','account_id','reservation_status','start_time','termination_time'
    ];

    public $timestamps = true;

    // 新規作成の際に初期データ生成
    public static function boot()
    {
        parent::boot();
        self::creating(function(t_projects $t_project){
            $t_project->project_uuid = Common::uuid();
        });
    }

    public function getClientNameAttribute()
    {
        $client = t_clients::whereClientId($this->client_id)->first();
        return $client->client_name;
    }

    public function getAccountNameAttribute()
    {
        $account = t_accounts::whereAccountId($this->account_id)->first();
        return $account->last_name.' '.$account->first_name;
    }

    public function getReservationStatusNameAttribute()
    {
        $reservation_status_name = '';
        if($this->reservation_status == 0)
        {
            $reservation_status_name = '仮予約';
        }
        elseif($this->reservation_status == 1)
        {
            $reservation_status_name = '本予約';
        }
        elseif($this->reservation_status == 2)
        {
            $reservation_status_name = '利用中';
        }
        elseif($this->reservation_status == 3)
        {
            $reservation_status_name = '利用終了待機';
        }
        elseif($this->reservation_status == 4)
        {
            $reservation_status_name = '利用終了';
        }
        elseif($this->reservation_status == 5)
        {
            $reservation_status_name = '利用終了(違約金支払い済み)';
        }
        elseif($this->reservation_status == 100)
        {
            $reservation_status_name = '違約金発生中';
        }

        return $reservation_status_name;
    }
}

laravel-app/app/Http/Controllers/Project/ProjectController.php
<?php

namespace App\Http\Controllers\Project;

use App\Models\t_accounts;
use App\Models\t_clients;
use App\Models\t_invoices;
use App\Models\t_projects;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProjectController extends Controller
{
    // プロジェクト一覧
    public function index(Request $request)
    {
        $page = [
            'title' => 'プロジェクト一覧',
            'dir' => ['project'],
        ];

        // TODO: データベースを叩く回数を極限まで減らす努力
        $projects = t_projects::all();
        foreach ($projects as $project)
        {
            $project->start_time = Carbon::parse($project->start_time)->format('Y年m月d日 H時');
            $project->termination_time = Carbon::parse($project->termination_time)->format('H時');
        }

        $data = [
            'page' => $page,
            'projects' => $projects,
        ];

        return view('project/index')->with($data);
    }

    // プロジェクト登録
    public function create(Request $request)
    {
        $page = [
            'title' => 'プロジェクト登録',
            'dir' => ['project','create'],
        ];

        $clients = t_clients::all();
        $accounts = t_accounts::all();

        $form = [
            'project_name' => '',
            'project_comment' => '',
            'client_id' => '',
            'account_id' => '',
            'use_day' => '',
            'start_hour' => '',
            'end_hour' => '',
            'project_amount' => '',
            'invoice_deadline' => '',
        ];


        $data = [
            'page' => $page,
            'clients' => $clients,
            'accounts' => $accounts,
            'form' => $form
        ];

        return view('project/create')->with($data);
    }

    // プロジェクト編集
    public function edit(Request $request)
    {
        $page = [
            'title' => 'プロジェクト編集',
            'dir' => ['project','edit'],
        ];

        if(!isset($request->uuid))
        {
            return redirect('/project');
        }

        $project = t_projects::whereProjectUuid($request->uuid)->first();
        $invoice = t_invoices::whereProjectId($project->project_id)
            ->whereInvoiceType(0)
            ->first();
        $clients = t_clients::all();
        $accounts = t_accounts::all();

        $form = [
            'project_name' => $project->project_name,
            'project_comment' => $project->project_comment,
            'client_id' => $project->client_id,
            'account_id' => $project->account_id,
            'use_day' => Carbon::parse($project->start_time)->format('Y年m月d日'),
            'start_hour' => Carbon::parse($project->start_time)->format('H'),
            'end_hour' => Carbon::parse($project->termination_time)->format('H'),
            'project_amount' => $invoice->invoice_amount,
            'invoice_deadline' => Carbon::parse($invoice->invoice_deadline)->format('Y年m月d日'),
        ];


        $data = [
            'page' => $page,
            'project' => $project,
            'clients' => $clients,
            'accounts' => $accounts,
            'form' => $form
        ];

        return view('project/edit')->with($data);
    }

    // プロジェクト詳細
    public function show(Request $request)
    {
        $page = [
            'title' => 'プロジェクト詳細',
            'dir' => ['project','show'],
        ];

        if(!isset($request->uuid))
        {
            return redirect('/project');
        }

        $project = t_projects::whereProjectUuid($request->uuid)->first();
        $invoices = t_invoices::whereProjectId($project->project_id)
            ->orderBy('created_at','desc')->get();

        // view用整形
        $project->use_day = Carbon::parse($project->start_time)->format('Y/m/d');
        $project->start_time = Carbon::parse($project->start_time)->format('H:i');
        $project->termination_time = Carbon::parse($project->termination_time)->format('H:i');
        $project->project_comment = $project->project_comment != '' ? $project->project_comment : 'コメントなし';
        foreach ($invoices as $invoice)
        {
            $invoice->invoice_comment = $invoice->invoice_comment != '' ? $invoice->invoice_comment : 'なし';
            $invoice->invoice_day = Carbon::parse($invoice->created_at)->format('Y/m/d');
        }

        $data = [
            'page' => $page,
            'project' => $project,
            'invoices' => $invoices,
        ];

        return view('project/show')->with($data);
    }
}

laravel-app/resources/views/project/index.blade.php
@extends('template.master')
@section('contents')
<!-- Content area -->
<div class="row">
    <div class="col-lg-7">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div style="position:absolute;">{{ $page['title'] }}</div>
                <div style="text-align: right"><span class="responsive-display-inline">検索： </span><input class="fm_search" type="text" placeholder="検索ワード" style="height:20px"></div>
            </div>
            <table id="datatables" class="table table-striped table-bordered table-hover">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>プロジェクト名</th>
                    <th>ステータス</th>
                    <th>顧客名</th>
                    <th>担当者</th>
                    <th>利用日時</th>
                </tr>
                </thead>
                <tbody id="sort_table">
                @foreach($projects as $key => $project)
                <tr class="list_tr">
                    <td>{{ $key+1 }}</td>
                    <td><span class="tx-project_name tx_link" data-uuid="{{ $project->project_uuid }}">{{ $project->project_name }}</span></td>
                    <td class="tx-project_status">{{ $project->reservation_status_name }}</td>
                    <td class="tx-client_name">{{ $project->client_name }}</td>
                    <td class="tx-staff_name">{{ $project->account_name }}</td>
                    <td class="tx-utilization_time">{{ $project->start_time }} ~ {{ $project->termination_time }}</td>
                </tr>
                @endforeach

                </tbody>
            </table>
        </div>
        <div class="responsive-display heading-text pull-right" style="margin-top:-10px;margin-bottom:50px;padding-right:10px;"><a href="/project/create"><img class="btn-img" src="/assets/img/btn/plus.png" width="50px" height="50px"></a></div>
    </div>
</div>
<!-- /main charts -->
@endsection
@section('scripts')
<script type="text/javascript">

    (function($){

        $(document).on('click', '.tx-project_name', function(){
            var uuid = $(this).attr('data-uuid');
            location.href = '/project/show?uuid=' + uuid;
        });

        $('.fm_search').on('input', function(){
            var search_range = ['tx-project_name','tx-project_status','tx-client_name','tx-staff_name','tx-utilization_time'];
            searchWord(search_range);
        });

        $('#datatables').addClass('nowrap').dataTable({
            responsive: true,
            lengthChange: false,
            searching: false,
            ordering: false,
            info: false,
            paging: false,
            language: {
                "paginate" : {
                    "first" : "先頭",
                    "previous" : "前へ",
                    "next" : "次へ",
                    "last" : "末尾"
                }
            }
        });

    })(jQuery);

</script>
@endsection

laravel-app/resources/views/project/show.blade.php
@extends('template.master')
@section('contents')
    <!-- Content area -->
    <div class="row">
        <div class="col-lg-7">
            <div class="deco panel panel-flat">
                <div class="panel-heading form_head deco">
                    <h5 class="panel-title">{{ $project->project_name }}</h5>
                    <input type="hidden" class="project_uuid" value="{{ $project->project_uuid }}">
                </div>
                <div class="panel-body deco">
                    <div class="deco form-group">
                        <div class="project-info">
                            <div class="project-info-left">
                                顧客名
                            </div>
                            <div class="project-info-right">
                                {{ $project->client_name }}
                            </div>
                            <div class="project-info-left">
                                利用日
                            </div>
                            <div class="project-info-right">
                                {{ $project->use_day }}
                            </div>
                            <div class="project-info-left">
                                利用時間
                            </div>
                            <div class="project-info-right">
                                {{ $project->start_time }} ~ {{ $project->termination_time }}
                            </div>
                            <div class="project-info-left">
                                担当者
                            </div>
                            <div class="project-info-right">
                                {{ $project->account_name }}
                            </div>
                            <div class="project-info-left">
                                予約ステータス
                            </div>
                            <div class="project-info-right">
                                {{ $project->reservation_status_name }}
                            </div>
                        </div>
                    </div>
                    <div class="deco form-group">
                        <label id="modal_label">コメント</label>
                        <div class="">
                            {{ $project->project_comment }}
                        </div>
                    </div>
                    <div class="deco form-group project-show-table">
                        <label id="modal_label">請求履歴</label>
                        <table class="project-show-table">
                            <tr>
                                <th>日時</th>
                                <th>状態</th>
                                <th>名前</th>
                                <th>金額</th>
                                <th>備考</th>
                                <th></th>
                            </tr>
                            @foreach($invoices as $key => $invoice)
                            <tr>
                                <td>{{ $invoice->invoice_day }}</td>
                                <td>{{ $invoice->invoice_status_name }}</td>
                                <td><span class="tx_link">{{ $invoice->invoice_name }}</span></td>
                                <td>{{ $invoice->invoice_amount }}円</td>
                                <td>{{ $invoice->invoice_comment }}</td>
                                <td>@if($invoice->invoice_status != 2)<button type="button" class="btn-payment btn btn-success" data-uuid="{{ $invoice->invoice_uuid }}">支払い</button>@endif</td>
                            </tr>
                            @endforeach
                            <tr class="btn-area">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td style="text-align: right;padding:0;"><img class="btn-invoice btn-img" src="/assets/img/btn/plus.png" width="25px" height="25px"></td>
                            </tr>
                        </table>
                    </div>
                    <div class="text-right">
                        <button type="button" class="btn-edit btn btn-primary">編集</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /main charts -->

<!-- Modal windoow -->
<div id="modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>
<!-- /Modal windoow -->
@endsection
@section('scripts')
    <script type="text/javascript">

        (function($){

            var uuid = $('.project_uuid').val();

            $(document).on('click', '.btn-payment', function(){
                location.href = '/invoice?uuid=' + $(this).attr('data-uuid');
            });

            $(document).on('click', '.btn-invoice', function(){
                location.href = '/invoice/create?uuid=' + uuid;
            });

            $(document).on('click', '.btn-edit', function(){
                location.href = '/project/edit?uuid=' + uuid;
            });

        })(jQuery);

    </script>
@endsection