laravel-app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// 認証関連
Route::get('/login','Auth\LoginController@showLoginForm');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout','Auth\LoginController@logout')->name('logout');
Auth::routes();

Route::group(['middleware' => ['auth']], function () {

    // ダッシュボード
    Route::get('/', 'Dashboard\DashboardController@index');

    // プロジェクト管理
    Route::get('/project', 'Project\ProjectController@index');
    Route::get('/project/create', 'Project\ProjectController@create');
    Route::post('/project/store', 'ReservationManagementController@storeProject');
    Route::get('/project/edit', 'Project\ProjectController@edit');
    Route::post('/project/update', 'Project\ProjectManagementController@update');
    Route::post('/project/checkHoliday', 'Project\ProjectManagementController@checkHoliday');
    Route::get('/project/show', 'Project\ProjectController@show');

    // 顧客管理
    Route::get('/client', 'Client\ClientController@index');
    Route::get('/client/create', 'Client\ClientController@create');
    Route::post('/client/store', 'ReservationManagementController@storeClient');
    Route::post('/client/storeQuick', 'ReservationManagementController@storeQuickClient');
    Route::get('/client/edit', 'Client\ClientController@edit');
    Route::post('/client/update', 'Client\ClientManagementController@update');
    Route::post('/client/show', 'Client\ClientManagementController@getClientData');

    // 請求管理
    Route::get('/invoice', 'Invoice\InvoiceController@index');
    Route::get('/invoice/create', 'Invoice\InvoiceController@create');
    Route::post('/invoice/store', 'ReservationManagementController@storeInvoice');
    Route::get('/invoice/edit', 'Invoice\InvoiceController@edit');
    Route::post('/invoice/update', 'Invoice\InvoiceManagementController@update');
    Route::post('/invoice/show', 'Invoice\InvoiceManagementController@getInvoiceData');

    // 入金管理
    Route::post('/payment', 'Payment\PaymentManagementController@payment');

    // 社員管理
    Route::get('/account','Account\AccountController@index');
    Route::get('/account/create','Account\AccountController@create');
    Route::post('/account/store','Account\AccountManagementController@store');
    Route::get('/account/edit','Account\AccountController@edit');
    Route::post('/account/update','Account\AccountManagementController@update');
    Route::get('/account/show', function () {

        $page = [
            'title' => '社員詳細',
            'dir' => ['account', 'show'],
        ];

        $data = [
            'page' => $page,
        ];

        return view('account/show')->with($data);
    });


    // 利用日当日
    Route::get('/use', 'Production\ProductionController@index');
    Route::post('/use/startUse', 'Production\ProductionManagementController@startUse');
    Route::post('/use/checkExtension', 'Production\ProductionManagementController@checkExtension');
    Route::post('/use/doExtension', 'Production\ProductionManagementController@doExtension');
    Route::post('/use/endStandbyUse', 'Production\ProductionManagementController@endStandbyUse');
    Route::post('/use/endUse', 'Production\ProductionManagementController@endUse');

});

// デバック
Route::get('/tr','Debug\DebugController@index');

// 初期画面
Route::get('/home', 'HomeController@index')->name('home');

laravel-app/app/Models/t_invoices.php
<?php

namespace App\Models;

use App\Libs\Common;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class t_invoices extends Model
{
    //
    protected $table = 't_invoices';
    protected $primaryKey = 'invoice_id';

    protected $fillable = [
        'project_id','board_project_code', 'board_invoice_code', 'board_estimate_code','board_receipt_code','invoice_name','invoice_type','invoice_amount','invoice_remain_amount','invoice_status','invoice_deadline'
    ];

    public $timestamps = true;

    // 新規作成の際に初期データ生成
    public static function boot()
    {
        parent::boot();
        self::creating(function(t_invoices $t_invoice){
            $t_invoice->invoice_uuid = Common::uuid();
        });
    }

    public function getInvoiceStatusNameAttribute()
    {
        $invoice_status_name = '';
        if($this->invoice_status == 0)
        {
            $invoice_status_name = '請求中';
        }
        elseif($this->invoice_status == 1)
        {
            $invoice_status_name = '請求中(一部支払い)';
        }
        elseif($this->invoice_status == 2)
        {
            $invoice_status_name = '支払い済み';
        }
        elseif($this->invoice_status == 100)
        {
            $invoice_status_name = '請求中(期日超過)';
        }

        return $invoice_status_name;
    }

    public function getInvoiceRemainDeadlineAttribute()
    {
        $remainDeadline = '';
        $today = Carbon::now();
        $deadline = Carbon::parse($this->invoice_deadline);

        if($today->gt($deadline) && $today->diffInDays($deadline)!=0)
        {
            $remainDeadline = '<b style="color:red">(超過'.$today->diffInDays($deadline).'日)</b>';
        }
        else if($today->diffInDays($deadline)<7 && $today->diffInDays($deadline)>0)
        {
            $remainDeadline = '<b>(残り'.$today->diffInDays($deadline).'日)</b>';
        }
        else if($today->diffInDays($deadline)==0)
        {
            $remainDeadline = '<b>(本日支払締切日)</b>';
        }

        return $remainDeadline;
    }

}

laravel-app/app/Http/Controllers/Invoice/InvoiceController.php
<?php

namespace App\Http\Controllers\Invoice;

use App\Models\t_invoices;
use App\Models\t_projects;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class InvoiceController extends Controller
{
    // 請求一覧
    public function index(Request $request)
    {
        $page = [
            'title' => '請求一覧',
            'dir' => ['invoice'],
        ];

        $invoices = t_invoices::all();

        foreach ($invoices as $invoice)
        {
            $invoice->invoice_deadline = Carbon::parse($invoice->invoice_deadline)->format('Y/m/d');
        }

        $invoice_uuid = '';
        if(isset($request->uuid))
        {
            $invoice_uuid = $request->uuid;
        }

        $data = [
            'page' => $page,
            'invoices' => $invoices,
            'invoice_uuid' => $invoice_uuid,
        ];

        return view('invoice/index')->with($data);
    }

    // 請求登録
    public function create(Request $request)
    {
        $page = [
            'title' => '請求登録',
            'dir' => ['invoice','create'],
        ];

        $projects = t_projects::all();

        $project_id = '';
        if(isset($request->uuid))
        {
            $project_id = t_projects::whereProjectUuid($request->uuid)->first()->project_id;
        }

        $form = [
            'project_id' => $project_id,
            'invoice_type' => '',
            'invoice_amount' => '',
            'invoice_deadline' => '',
        ];

        $data = [
            'page' => $page,
            'projects' => $projects,
            'form' => $form,
        ];

        return view('invoice/create')->with($data);
    }

    // 請求登録
    public function edit(Request $request)
    {
        $page = [
            'title' => '請求編集',
            'dir' => ['invoice','edit'],
        ];

        if(!isset($request->uuid))
        {
            return redirect('/invoice');
        }

        $projects = t_projects::all();
        $invoice = t_invoices::whereInvoiceUuid($request->uuid)->first();

        $form = [
            'project_id' => $invoice->project_id,
            'invoice_type' => $invoice->invoice_type,
            'invoice_amount' => $invoice->invoice_amount,
            'invoice_deadline' => Carbon::parse($invoice->invoice_deadline)->format('Y年m月d日'),
        ];

        $data = [
            'page' => $page,
            'projects' => $projects,
            'invoice' => $invoice,
            'form' => $form,
        ];

        return view('invoice/edit')->with($data);
    }
}

laravel-app/resources/views/invoice/create.blade.php
@extends('template.master')
@section('contents')
<!-- Content area -->
<div class="row">
    <div class="col-lg-7">
        <div class="col-md-15">

            <!-- Basic layout-->
            <form action="/invoice/store" name="" id="" method="post">
                <div class="fm_project deco panel panel-flat">
                    <div class="panel-heading form_head">
                        @if(\Illuminate\Support\Facades\Session::has('flash_message_success'))
                            <ul class="validation alert alert-success list-unstyled">
                                <li>{{ \Illuminate\Support\Facades\Session::get('invoice-name') }}の登録が完了しました。</li>
                            </ul>
                        @endif
                        @if(count($errors) > 0)
                            <ul class="validation alert alert-danger list-unstyled">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif
                        <h5 class="panel-title">{{ $page['title'] }}</h5>
                    </div>

                    <div class="panel-body">
                        <div class="form-group">
                            <label class="control-label" for="">プロジェクト選択</label>
                            <select data-placeholder="" name="project_id" class="chosen-select select-project-id form-control" id="">
                                <option value="">-- 選択してください --</option>
                                @foreach($projects as $key => $project)
                                <option value="{{ $project->project_id }}" @if(old('project_id',$form['project_id']==$project->project_id)) selected @endif>{{ $project->project_name }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="">請求タイプ</label>
                            <select name="invoice_type" class="select-invoice-type form-control" id="">
                                <option value="">-- 請求タイプを選択してください --</option>
                                <option value="1" @if(old('invoice_type',$form['invoice_type']==1)) selected @endif>利用延長料</option>
                                <option value="2" @if(old('invoice_type',$form['invoice_type']==2)) selected @endif>違約金</option>
                                <option value="3" @if(old('invoice_type',$form['invoice_type']==3)) selected @endif>その他</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>請求金額</label>
                            <input type="number" name="invoice_amount" class="invoice-amount form-control" placeholder="数字のみ入力してください。" value="{{ old('invoice_amount',$form['invoice_amount']) }}" required />
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="">料金受付締切日選択</label>
                            <fieldset class="fieldset">
                                <input name="invoice_deadline" class="select-deadline-day form-control" id="select-deadline-day" type="text" value="{{ old('invoice_deadline',$form['invoice_deadline']) }}">
                            </fieldset>
                        </div>

                        <div class="text-right">
                            {{ csrf_field() }}
                            <button type="submit" class="btn-submit btn btn-primary">登録</button>
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /main charts -->

<!-- Modal windoow -->
<div id="modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>
<!-- /Modal windoow -->
@endsection
@section('scripts')
<script type="text/javascript">

    (function($){

        $('#select-deadline-day').pickadate();

    })(jQuery);
</script>
@endsection

laravel-app/resources/views/invoice/edit.blade.php
@extends('template.master')
@section('contents')
    <!-- Content area -->
    <div class="row">
        <div class="col-lg-7">
            <div class="col-md-15">

                <!-- Basic layout-->
                <form action="/invoice/update" name="" id="" method="post">
                    <div class="fm_project deco panel panel-flat">
                        <div class="panel-heading form_head">
                            @if(\Illuminate\Support\Facades\Session::has('flash_message_success'))
                                <ul class="validation alert alert-success list-unstyled">
                                    <li>{{ \Illuminate\Support\Facades\Session::get('invoice-name') }}の登録が完了しました。</li>
                                </ul>
                            @endif
                            @if(count($errors) > 0)
                                <ul class="validation alert alert-danger list-unstyled">
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif
                            <h5 class="panel-title">{{ $page['title'] }}</h5>
                        </div>

                        <div class="panel-body">
                            <div class="form-group">
                                <label class="control-label" for="">プロジェクト選択</label>
                                <select data-placeholder="" name="project_id" class="chosen-select select-project-id form-control" id="">
                                    <option value="">-- 選択してください --</option>
                                    @foreach($projects as $key => $project)
                                        <option value="{{ $project->project_id }}" @if(old('project_id',$form['project_id']==$project->project_id)) selected @endif>{{ $project->project_name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="">請求タイプ</label>
                                <select name="invoice_type" class="select-invoice-type form-control" id="">
                                    <option value="">-- 請求タイプを選択してください --</option>
                                    <option value="0" @if(old('invoice_type',$form['invoice_type']==0)) selected @endif>利用料</option>
                                    <option value="1" @if(old('invoice_type',$form['invoice_type']==1)) selected @endif>利用延長料</option>
                                    <option value="2" @if(old('invoice_type',$form['invoice_type']==2)) selected @endif>違約金</option>
                                    <option value="3" @if(old('invoice_type',$form['invoice_type']==3)) selected @endif>その他</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label>請求金額</label>
                                <input type="number" name="invoice_amount" class="invoice-amount form-control" placeholder="数字のみ入力してください。" value="{{ old('invoice_amount',$form['invoice_amount']) }}" required />
                            </div>

                            <div class="form-group">
                                <label class="control-label" for="">料金受付締切日選択</label>
                                <fieldset class="fieldset">
                                    <input name="invoice_deadline" class="select-deadline-day form-control" id="select-deadline-day" type="text" value="{{ old('invoice_deadline',$form['invoice_deadline']) }}">
                                </fieldset>
                            </div>

                            <div class="text-right">
                                {{ csrf_field() }}
                                <input type="hidden" name="invoice_uuid" value="{{ $invoice->invoice_uuid }}">
                                <button type="submit" class="btn-submit btn btn-primary">登録</button>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /main charts -->

    <!-- Modal windoow -->
    <div id="modal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <!-- /Modal windoow -->
@endsection
@section('scripts')
    <script type="text/javascript">

        (function($){

            $('#select-deadline-day').pickadate();

        })(jQuery);
    </script>
@endsection

laravel-app/resources/views/invoice/index.blade.php
@extends('template.master')
@section('contents')
<!-- Content area -->
<div class="row">
    <div class="col-lg-7">
        <div class="panel panel-success">
            <div class="panel-heading">
                <div style="position:absolute;">{{ $page['title'] }}</div>
                <div style="text-align: right"><span class="responsive-display-inline">検索： </span><input class="fm_search" type="text" placeholder="検索ワード" style="height:20px"></div>
            </div>
            <table id="datatables" class="table table-striped table-bordered table-hover table-bill">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>請求内容</th>
                    <th>金額</th>
                    <th>ステータス</th>
                    <th>支払い期間</th>
                    <th></th>
                </tr>
                </thead>
                <tbody id="sort_table">
                @foreach($invoices as $key => $invoice)
                <tr class="list_tr">
                    <td>{{ $key+1 }}</td>
                    <td class="tx-bill_type tx_link" data-uuid="{{ $invoice->invoice_uuid }}">{{ $invoice->invoice_name }}</td>
                    <td class="tx-bill_amount">{{ $invoice->invoice_amount }}円</td>
                    <td class="tx-bill_status">{{ $invoice->invoice_status_name }}</td>
                    <td class="tx-bill-deadline">~{{ $invoice->invoice_deadline }} {!! $invoice->invoice_remain_deadline !!}</td>
                    <td><button type="button" class="btn-edit btn btn-primary" data-uuid="{{ $invoice->invoice_uuid }}">編集</button></td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div class="responsive-display heading-text pull-right" style="margin-top:-10px;margin-bottom:50px;padding-right:10px;"><a href="/invoice/create"><img class="btn-img" src="/assets/img/btn/plus.png" width="50px" height="50px"></a></div>
        <input type="hidden" class="invoice_uuid" value="{{ $invoice_uuid }}">
    </div>
</div>
<!-- /main charts -->

<!-- Modal windoow -->
<div id="modal" class="modal modal-bill fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="deco modal-header">
                <ul class="disp_error alert alert-danger list-unstyled" style="display: none;"></ul>
                <h5 class="modal-title" id="modal_title" style="position: absolute">請求詳細</h5>
                <h5 class="bt_change modal-title" data-dismiss="modal" style="margin:0 20px 0 0px;text-align: right;display: block"><span class="change_show1 bt_link">×</span></h5>
            </div>
            <div id="" style="display: block">
                <div class="modal-body">

                    <div class="modal-info">
                        <div class="modal-info-left">
                            請求内容
                        </div>
                        <div class="modal-info-right">
                            <span class="mdl-invoice_title"></span>
                        </div>
                        <div class="modal-info-left">
                            金額
                        </div>
                        <div class="modal-info-right">
                            <span class="mdl-invoice_amount"></span><span class="mdl-invoice_remain_amount"></span>
                        </div>
                        <div class="modal-info-left">
                            状態
                        </div>
                        <div class="modal-info-right">
                            <span class="mdl-invoice_status_name"></span>
                        </div>
                        <div class="modal-info-left">
                            受付期間
                        </div>
                        <div class="modal-info-right">
                            <span class="mdl-invoice_deadline"></span>
                        </div>
                        <div class="modal-info-left">
                            該当プロジェクト名
                        </div>
                        <div class="modal-info-right">
                            <span class="mdl-invoice_project_name"></span>
                        </div>
                        <div class="modal-info-left">
                            該当顧客名
                        </div>
                        <div class="modal-info-right">
                            <span class="mdl-invoice_client_name"></span>
                        </div>

                    </div>

                    <div class="btn-doc-area">
                        <button type="button" class="btn-quotation btn btn-success">見積書</button>
                        <button type="button" class="btn-invoice btn btn-primary">請求書</button>
                        <button type="button" class="btn-receipt btn btn-warning">領収書</button>
                    </div>

                    <div class="pay-area">
                        <div class="inline-block">【支払い処理】</div>
                        <div class="fm-pay-area inline-block"><input name="payment_amount" class="fm_pay payment_amount" type="text" placeholder="" style="height:20px"> 円</div>
                        <div class="inline-block"><button type="button" class="mdl-btn-payment btn-pay btn btn-danger" data-uuid="">支払う</button></div>
                    </div>

                    <div class="deco form-group">
                        <label id="modal_label">支払い履歴</label>
                        <table class="modal-table modal-payments-table">
                        </table>
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" class="mdl_uuid" value="">
                <button type="button" class="btn-edit mdl-btn-edit btn btn-primary" data-uuid="">編集</button>
            </div>
        </div>
    </div>
</div>
<!-- /Modal windoow -->
@endsection
@section('scripts')
<script type="text/javascript">

    (function($){

        if($('.invoice_uuid').val() != '')
        {
            showInvoiceData($('.invoice_uuid').val());
        }

        $(document).on('click', '.tx-bill_type', function(){
            var uuid = $(this).attr('data-uuid');
            showInvoiceData(uuid);
        });

        $(document).on('click', '.btn-quotation', function(){
            alert('見積書発行処理');
        });

        $(document).on('click', '.btn-invoice', function(){
            alert('請求書発行処理');
        });

        $(document).on('click', '.btn-receipt', function(){
            alert('領収書発行処理');
        });

        $(document).on('click', '.btn-pay', function(){

            var pay_amount = Number($('.fm_pay').val());
            var uuid = $(this).attr('data-uuid');

            if(pay_amount!=NaN && Number.isInteger(pay_amount) && pay_amount>0)
            {
                if(confirm(pay_amount+'円の支払いを確定します。よろしければOKを押してください。'))
                {
                    runPayment(uuid,pay_amount);
                }
                else{
                    return true;
                }
            }
            else{
                alert('正しい金額を入力して下さい。');
            }
        });

        $(document).on('click', '.btn-edit', function(){
            var uuid = $(this).attr('data-uuid');
            location.href = '/invoice/edit?uuid=' + uuid;
        });

        $('.fm_search').on('input', function(){
            var search_range = ['tx-bill_type','tx-bill_amount','tx-bill_status','tx-bill-deadline'];
            searchWord(search_range);
        });

        $('#datatables').addClass('nowrap').dataTable({
            responsive: true,
            lengthChange: false,
            searching: false,
            ordering: false,
            info: false,
            paging: false,
            language: {
                "paginate" : {
                    "first" : "先頭",
                    "previous" : "前へ",
                    "next" : "次へ",
                    "last" : "末尾"
                }
            }
        });

    })(jQuery);

    function showInvoiceData(uuid)
    {
        var data = {
            uuid: uuid
        };

        $.ajax({
            url: '/invoice/show',
            type: "post",
            contentType: 'application/json',
            data: JSON.stringify(data),
            dataType: 'json'
        }).done(function(data, textStatus, jqXHR){
            if(data.status == 1)
            {
                // OK
                resetModal();
                console.log(data.view_data.payments);
                $('.mdl-invoice_title').text(data.view_data.invoice.invoice_name);
                $('.mdl-invoice_amount').text(data.view_data.invoice.invoice_amount + '円');

                if(data.view_data.invoice.invoice_amount != data.view_data.invoice.invoice_remain_amount && data.view_data.invoice.invoice_remain_amount != 0)
                {
                    $('.mdl-invoice_remain_amount').text(' (残り'+data.view_data.invoice.invoice_remain_amount+'円)');
                }

                $('.mdl-invoice_status_name').text(data.view_data.invoice.invoice_view_status_name);
                $('.mdl-invoice_deadline').text('~' + data.view_data.invoice.invoice_deadline);
                $('.mdl-invoice_project_name').text(data.view_data.invoice.invoice_project_name);
                $('.mdl-invoice_client_name').text(data.view_data.invoice.invoice_client_name);
                $('.payment_amount').attr('placeholder',data.view_data.invoice.invoice_remain_amount);
                $('.mdl-btn-payment').attr('data-uuid',data.view_data.invoice.invoice_uuid);
                $('.mdl-btn-edit').attr('data-uuid',data.view_data.invoice.invoice_uuid);
                if(data.view_data.payments.length == 0)
                {
                    $('.modal-payments-table').prepend(
                        $('<tr></tr>')
                            .append($('<td></td>').text('支払い履歴はありません。'))
                    );
                }
                else
                {
                    var remain_amount = data.view_data.invoice.invoice_amount;
                    for(var i=0;i<data.view_data.payments.length;i++)
                    {
                        remain_amount = remain_amount - data.view_data.payments[i].payment_amount;
                        var time_text = generateTimeText(data.view_data.payments[i].created_at);
                        $('.modal-payments-table').prepend(
                            $('<tr></tr>')
                                .append($('<td></td>').text(time_text))
                                .append($('<td></td>').text(data.view_data.payments[i].payment_amount + '円'))
                                .append($('<td></td>').text('残り'+remain_amount+'円'))
                        );
                    }
                }

                $('#modal').modal('show');
            }
            else
            {
                // NG
                alert('fatal error');
            }
        }).fail(function(data, textStatus, errorThrown){
            alert('connection error');
        });
    }

    function resetModal()
    {
        $('.mdl-invoice_title').text('');
        $('.mdl-invoice_amount').text('');
        $('.mdl-invoice_remain_amount').text('');
        $('.mdl-invoice_status_name').text('');
        $('.mdl-invoice_deadline').text('');
        $('.mdl-invoice_project_name').text('');
        $('.mdl-invoice_client_name').text('');
        $('.payment_amount').val('');
        $('.payment_amount').attr('placeholder','');
        $('.mdl-btn-edit').attr('data-uuid','');
        $('.modal-payments-table').empty();
    }

    function runPayment(uuid,payment_amount)
    {
        var data = {
            uuid: uuid,
            payment_amount: payment_amount
        };

        $.ajax({
            url: '/payment',
            type: "post",
            contentType: 'application/json',
            data: JSON.stringify(data),
            dataType: 'json'
        }).done(function(data, textStatus, jqXHR){
            if(data.status == 1)
            {
                // OK
                alert(payment_amount + '円の支払いを確定しました。');
                $('#modal').modal('hide');
                location.href = '/invoice?uuid=' + uuid;
            }
            else
            {
                // NG
                alert(data.message);
            }
        }).fail(function(data, textStatus, errorThrown){
            alert('connection error');
        });
    }

    function generateTimeText(timeStamp)
    {
        var timeText = moment(timeStamp).format('YYYY/MM/DD');

        return timeText;
    }

</script>
@endsection